version: 2.1

ruby_25_pg_11: &ruby_25_pg_11
  - image: ruby:2.5
    environment:
      PG_VERSION: "11.9"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
  - image: circleci/postgres:11-alpine

setup_git_user: &setup_git_user
  run:
    name: Setup Git User
    command: |
      git config --global user.name "Prodder In Travis-CI"
      git config --global user.email "prodder@example.com"

setup_db: &setup_db
  run:
    name: Setup DB
    command: |
      ln -sfn /usr/lib/postgresql/$PG_VERSION/bin/pg_dump /usr/bin/pg_dump
      ls -al `which pg_dump`
      psql -U postgres -d postgres -c 'select setting from pg_settings where name = $m$server_version$m$;'
      psql --version
      pg_lsclusters
      psql -U postgres -d postgres -c 'select 1;'

master_only_filter: &master_only_filter
  filters:
    branches:
      only: master

master_ignore_filter: &master_ignore_filter
  filters:
    branches:
      ignore: master

jobs:
  ruby_25_pg_11_rspec:
    docker: *ruby_25_pg_11
    steps:
      - *setup_git_user
      - *setup_db
      - run: bundle exec rake spec

workflows:
  ruby_25_pg_11_tests:
    jobs:
      - ruby_25_pg_11_rspec