version: 2.1

ruby_25: &ruby_25
  - image: ruby:2.5
    environment:
      PG_VERSION: "11.9"
      POSTGRES_USER: postgres

setup_git_user: &setup_git_user
  run:
    name: Setup Git User
    command: |
      git config --global user.name "Prodder In Travis-CI"
      git config --global user.email "prodder@example.com"

install_libs: &install_libs
  run:
    name: Install linux libraries
    command: |
      apt-get update
      apt-get install -y libpq-dev libpq5 libmagic-dev postgresql-client postgresql
      gem install bundler:1.17.3

setup_db: &setup_db
  run:
    name: Setup DB
    command: |
      ln -sfn /usr/lib/postgresql/$PG_VERSION/bin/pg_dump /usr/bin/pg_dump
      service postgresql stop
      sleep 5s
      service postgresql start $PG_VERSION
      psql -U postgres -d postgres -c 'select setting from pg_settings where name = $m$server_version$m$;'
      psql --version
      pg_lsclusters
      psql -U postgres -d postgres -c 'select 1;'
      ls -al `which pg_dump`

master_only_filter: &master_only_filter
  filters:
    branches:
      only: master

master_ignore_filter: &master_ignore_filter
  filters:
    branches:
      ignore: master

jobs:
  ruby_25_pg_11_rspec:
    docker: *ruby_25
    steps:
      - checkout
      - *setup_git_user
      - *install_libs
      - *setup_db
      - run: bundle exec rake spec

workflows:
  ruby_25_pg_11_tests:
    jobs:
      - ruby_25_pg_11_rspec